-- NIGHT CITY // friend messages
-- Chat entre contas autenticadas.

create table if not exists public.friend_messages (
  id bigint generated by default as identity primary key,
  channel_id text not null,
  sender text not null,
  receiver text not null,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists friend_messages_channel_created_idx
  on public.friend_messages(channel_id, created_at);

create index if not exists friend_messages_receiver_idx
  on public.friend_messages(receiver);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'friend_messages'
  ) then
    alter publication supabase_realtime add table public.friend_messages;
  end if;
end $$;

alter table public.friend_messages enable row level security;

drop policy if exists "friend_messages_own_select" on public.friend_messages;
drop policy if exists "friend_messages_own_insert" on public.friend_messages;

revoke all on public.friend_messages from anon;
grant select, insert on public.friend_messages to authenticated;

create policy "friend_messages_own_select"
  on public.friend_messages
  for select
  to authenticated
  using (sender = auth.uid()::text or receiver = auth.uid()::text);

-- ---------------------------------------------------------------------------
-- SECURITY GAP (documented): no accepted-relationship table exists in schema.
-- ---------------------------------------------------------------------------
-- Ideally the INSERT policy would also require an *accepted* friendship between
-- sender and receiver, so a user cannot message arbitrary accounts. However,
-- inspecting the full Supabase schema (friend-messages.sql, friend-profiles.sql,
-- push-notifications.sql, security-hardening.sql) there is NO friend_requests /
-- relationships / friendships table and NO status='accepted' column anywhere.
-- The Commlink search directory is now `public.friend_profile_directory`, which
-- exposes only owner/nick/tag/name/level and carries no relationship state.
--
-- Because no authoritative accepted-relationship source exists, we cannot yet
-- enforce a correct mutual-friendship check. The conservative `with check`
-- below keeps the existing sender-identity guarantee. The commented EXISTS
-- block is a TEMPLATE for when a relationship table is introduced: it assumes a
-- table `public.friend_requests(requester text, addressee text, status text)`
-- with status='accepted' for an established friendship in either direction.
-- DO NOT enable it until that table actually exists and column names are
-- confirmed, otherwise every INSERT will fail.
create policy "friend_messages_own_insert"
  on public.friend_messages
  for insert
  to authenticated
  with check (
    sender = auth.uid()::text
    -- TEMPLATE (disabled): require an accepted friendship between the two users.
    -- and exists (
    --   select 1
    --   from public.friend_requests fr
    --   where fr.status = 'accepted'
    --     and (
    --       (fr.requester = sender   and fr.addressee = receiver) or
    --       (fr.requester = receiver and fr.addressee = sender)
    --     )
    -- )
  );
