-- NIGHT CITY // friend messages
-- Chat entre contas autenticadas.

create table if not exists public.friend_messages (
  id bigint generated by default as identity primary key,
  channel_id text not null,
  sender text not null,
  receiver text not null,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists friend_messages_channel_created_idx
  on public.friend_messages(channel_id, created_at);

create index if not exists friend_messages_receiver_idx
  on public.friend_messages(receiver);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'friend_messages'
  ) then
    alter publication supabase_realtime add table public.friend_messages;
  end if;
end $$;

alter table public.friend_messages enable row level security;

drop policy if exists "friend_messages_own_select" on public.friend_messages;
drop policy if exists "friend_messages_own_insert" on public.friend_messages;

revoke all on public.friend_messages from anon;
grant select, insert on public.friend_messages to authenticated;

create policy "friend_messages_own_select"
  on public.friend_messages
  for select
  to authenticated
  using (sender = auth.uid()::text or receiver = auth.uid()::text);

create policy "friend_messages_own_insert"
  on public.friend_messages
  for insert
  to authenticated
  with check (sender = auth.uid()::text);
