-- Night City Web Push tables
-- Rode no SQL editor do Supabase antes de ativar o modo tela fechada.

create table if not exists public.push_subscriptions (
  endpoint text primary key,
  username text not null,
  subscription jsonb not null,
  user_agent text,
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_username_idx on public.push_subscriptions(username);

create table if not exists public.push_delivery_log (
  id bigint generated by default as identity primary key,
  endpoint text not null,
  username text not null,
  reminder_id text not null,
  delivery_date date not null,
  status text not null default 'sent',
  error text,
  created_at timestamptz not null default now(),
  unique(endpoint, reminder_id, delivery_date)
);

alter table public.push_delivery_log add column if not exists status text not null default 'sent';
alter table public.push_delivery_log add column if not exists error text;

alter table public.push_subscriptions enable row level security;
alter table public.push_delivery_log enable row level security;

-- A funcao Edge usa SERVICE_ROLE_KEY e ignora RLS.
-- O cliente autenticado gerencia apenas a propria inscricao.
drop policy if exists "push_subscriptions_upsert_anon" on public.push_subscriptions;
drop policy if exists "push_subscriptions_own_select" on public.push_subscriptions;
drop policy if exists "push_subscriptions_own_insert" on public.push_subscriptions;
drop policy if exists "push_subscriptions_own_update" on public.push_subscriptions;
drop policy if exists "push_subscriptions_own_delete" on public.push_subscriptions;

revoke all on public.push_subscriptions from anon;
grant select, insert, update, delete on public.push_subscriptions to authenticated;

create policy "push_subscriptions_own_select"
  on public.push_subscriptions
  for select
  to authenticated
  using (username = auth.uid()::text);

create policy "push_subscriptions_own_insert"
  on public.push_subscriptions
  for insert
  to authenticated
  with check (username = auth.uid()::text);

create policy "push_subscriptions_own_update"
  on public.push_subscriptions
  for update
  to authenticated
  using (username = auth.uid()::text)
  with check (username = auth.uid()::text);

create policy "push_subscriptions_own_delete"
  on public.push_subscriptions
  for delete
  to authenticated
  using (username = auth.uid()::text);
