-- Night City Web Push tables
-- Rode no SQL editor do Supabase antes de ativar o modo tela fechada.

create table if not exists public.push_subscriptions (
  endpoint text primary key,
  username text not null,
  subscription jsonb not null,
  user_agent text,
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_username_idx on public.push_subscriptions(username);

create table if not exists public.push_delivery_log (
  id bigint generated by default as identity primary key,
  endpoint text not null,
  username text not null,
  reminder_id text not null,
  delivery_date date not null,
  created_at timestamptz not null default now(),
  unique(endpoint, reminder_id, delivery_date)
);

alter table public.push_subscriptions enable row level security;
alter table public.push_delivery_log enable row level security;

-- A funcao Edge usa SERVICE_ROLE_KEY e ignora RLS.
-- O cliente anon precisa apenas inserir/atualizar a propria inscricao.
drop policy if exists "push_subscriptions_upsert_anon" on public.push_subscriptions;
create policy "push_subscriptions_upsert_anon"
  on public.push_subscriptions
  for all
  using (true)
  with check (true);
