-- NIGHT CITY // deprecated compatibility shim
--
-- The final production hardening is now in:
--   supabase/security-hardening.sql
--
-- This file intentionally contains no executable policy. Apply the final
-- hardening file above instead.
